/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '@browser': RouteRecordInfo<
      '@browser',
      '/:bucket/:path(.*)?',
      { bucket: ParamValue<true>, path?: ParamValueZeroOrOne<true> },
      { bucket: ParamValue<false>, path?: ParamValueZeroOrOne<false> },
      | never
    >,
    '@upload-standalone': RouteRecordInfo<
      '@upload-standalone',
      '/:bucket/@upload',
      { bucket: ParamValue<true> },
      { bucket: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'frontend/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'frontend/pages/[bucket]/[[...path]].vue': {
      routes:
        | '@browser'
      views:
        | never
    }
    'frontend/pages/[bucket]/@upload.vue': {
      routes:
        | '@upload-standalone'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
