/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrowserFilePreview: typeof import('./components/Browser/BrowserFilePreview.vue')['default']
    BrowserGalleryView: typeof import('./components/Browser/BrowserGalleryView.vue')['default']
    BrowserGridView: typeof import('./components/Browser/BrowserGridView.vue')['default']
    BrowserListView: typeof import('./components/Browser/BrowserListView.vue')['default']
    BrowserPreviewModal: typeof import('./components/Browser/BrowserPreviewModal.vue')['default']
    BrowserUploadHistory: typeof import('./components/Browser/BrowserUploadHistory.vue')['default']
    GlobalFooter: typeof import('./components/Global/GlobalFooter.vue')['default']
    GlobalHeader: typeof import('./components/Global/GlobalHeader.vue')['default']
    Hljs: typeof import('./components/Hljs.vue')['default']
    NA: typeof import('naive-ui')['NA']
    NaiveuiProvider: typeof import('./components/NaiveuiProvider.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NButtonLink: typeof import('./components/NButtonLink.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NCode: typeof import('naive-ui')['NCode']
    NCollapseTransition: typeof import('naive-ui')['NCollapseTransition']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NFloatButtonGroup: typeof import('naive-ui')['NFloatButtonGroup']
    NForm: typeof import('naive-ui')['NForm']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NModal: typeof import('naive-ui')['NModal']
    NP: typeof import('naive-ui')['NP']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NRouterLink: typeof import('./components/NRouterLink.vue')['default']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpin: typeof import('naive-ui')['NSpin']
    NTable: typeof import('naive-ui')['NTable']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadForm: typeof import('./components/UploadForm.vue')['default']
  }
}
