/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NAlert: typeof import('naive-ui')['NAlert']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCode: typeof import('naive-ui')['NCode']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const NAlert: typeof import('naive-ui')['NAlert']
  const NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
  const NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
  const NButton: typeof import('naive-ui')['NButton']
  const NButtonGroup: typeof import('naive-ui')['NButtonGroup']
  const NCard: typeof import('naive-ui')['NCard']
  const NCheckbox: typeof import('naive-ui')['NCheckbox']
  const NCode: typeof import('naive-ui')['NCode']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDataTable: typeof import('naive-ui')['NDataTable']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NDivider: typeof import('naive-ui')['NDivider']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NInput: typeof import('naive-ui')['NInput']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NModal: typeof import('naive-ui')['NModal']
  const NModalProvider: typeof import('naive-ui')['NModalProvider']
  const NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}